##Pablz's zshrc

#SETUP
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e

zstyle :compinstall filename '~/.zshrc'
autoload -Uz compinit
compinit

##GIT SETUP
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
zstyle ':vcs_info:*' check-for-changes true
#zstyle ':vcs_info:git:*' formats '%s %b'
zstyle ':vcs_info:git*' formats "%{$fg[yellow]%}%{$reset_color%} (%r/%b %m%u%c)"

#PROMPT
PROMPT="[%n@%B%F{green}%m%f%b:%F{green}%~%f]$ "
RPROMPT='${vcs_info_msg_0_}'

##PLUGINS ZPLUG
export ZPLUG_HOME=/home/pablo/.config/zplug
source $ZPLUG_HOME/init.zsh

zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting"

##START
nerdfetch
echo ""

#ALIASES
alias nv='nvim'
alias vim='nvim'
alias ll='lsd -l'
alias la='lsd -la'
alias ls='lsd'
alias tree='tree -C'
alias pablo='clear && source ~/.zshrc'
