#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

##Alice config
picom -b --animations --animation-window-mass 0.5 --animation-for-open-window zoom --animation-stiffness 350 &
nitrogen --restore
tilda &
xsetroot -cursor_name left_ptr &
exec ~/.config/polybar/launch.sh &


bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Alacritty desktop='^1'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
